name: preference-elicitation

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - pip
  - matplotlib
  - pandas
  - jupyter
  - choix
  - pip:
    - wandb
